### ISSUE TITLE
图片不考虑压缩一下

### ISSUE THREAD

**Issue by iceprosurface** [KarDia-C/kardia-c.github.io#1]
里面的png图片真的不考虑压缩一下嘛，这里有免费的网站提供压缩服务：

https://tinyjpg.com/

效果可以达到 60 ~ 70% 且画质丢失非常小

**Comment by DavidDiao** [comment]
这要整个改了的话，似乎对app用户不是很友好呢。。

**Comment by iceprosurface** [comment]
为啥会对 app 用户会有影响啊，不是只是压缩了一下大小么。。

**Comment by DavidDiao** [comment]
emmm这样的话 app要把 所有 图片都更新一遍啊
现在app的更新写的是跟你游类似的 一个一个更新所有有更新的文件 然后图都换一批的话。。就。。要更新好久。。
也没写什么强制更新客户端 甚至可能大部分人都不知道app到哪下（传播方式主要是群文件），所以让用户都去找新版本更新也不现实
我觉得等结合部官网开始搭了再说？

**Comment by iceprosurface** [comment]
原来是这样，我想的是 web 那边载入很慢，可以压缩一下图缓解一下，另外web那边如果主要适配 chrome 的话可以考虑用 workbox 考虑做 cache 以保证 离线/资源 无法访问情况下的可达性。

参考：

https://developers.google.com/web/tools/workbox/

然后我这边在做一个 你这个 app 的换皮版本2333，要是官网需要技术支持的阔以 @一起来搞~

**Comment by DavidDiao** [comment]
整好了
